language: python
before_install:
- pip install awscli
install:
- make init
script:
- make plan
after_deploy:
- make apply invalidate
deploy:
- provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: sctu.net
  local-dir: www
  acl: private
  on:
    repo: somerville-cambridge-tenants-union/sctu.net
    tags: true
