version: '3'

services:

  aws:
    entrypoint: aws
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
    image: lambci/lambda:build-python3.7
    volumes:
      - ./www:/var/task/www

  terraform:
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
    image: hashicorp/terraform
    volumes:
      - ./:/var/task
      - terraform:/var/task/.terraform
    working_dir: /var/task

volumes:
  terraform:
