name: plan
on:
  pull_request:
  push:
    branches:
      - '*'
  schedule:
    - cron: "11 21 * * *"
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform plan
